blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://elemn.to/gh-new-feature-request
    about: Suggest new ideas, features, or enhancements for the Elementor plugin.
  - name: ğŸ›Ÿ Get Support
    url: https://elemn.to/support-ticket
    about: Need Help, Assistance, or Support? Follow these instructions.
  - name: ğŸ“ Elementor Academy
    url: https://elemn.to/academy
    about: Learn everything you need to know about using Elementor.
  - name: ğŸ—¨ï¸ Elementor Global Community
    url: https://elemn.to/fb
    about: The main Facebook group where all kinds of users come together to help each other.
  - name: ğŸ“š Elementor Developers Center
    url: https://elemn.to/dev-center
    about: Technical information and Elementor developers docs. Learn everything about extending Elementor.
  - name: ğŸŒ Elementor Developers Community
    url: https://elemn.to/dev-community
    about: Share tips, tricks and knowledge with other developers about extending and developing for Elementor.
  - name: ğŸ“– Contributing Guidelines
    url: https://elemn.to/gh-contributing
    about: Before filing a bug report, a feature request or sending pull requests, be sure to read the Contribution Guidelines.
  - name: ğŸ¤ Code of Conduct
    url: https://elemn.to/gh-code-of-conduct
    about: To foster a safe, open, and welcoming environment, we have a Code of Conduct that should be followed by all participants.
